package basic

//go:generate sed -i ".bak" "s/\\+build none/generated by gotemplate/" template/BasicType.go
//go:generate gotemplate -outfmt %v "github.com/reddyvinod/partialencode/basic/template" Int(int)
//go:generate gotemplate -outfmt %v "github.com/reddyvinod/partialencode/basic/template" Uint(uint)

//go:generate gotemplate -outfmt %v "github.com/reddyvinod/partialencode/basic/template" Int8(int8)
//go:generate gotemplate -outfmt %v "github.com/reddyvinod/partialencode/basic/template" Int16(int16)
//go:generate gotemplate -outfmt %v "github.com/reddyvinod/partialencode/basic/template" Int32(int32)
//go:generate gotemplate -outfmt %v "github.com/reddyvinod/partialencode/basic/template" Int64(int64)

//go:generate gotemplate -outfmt %v "github.com/reddyvinod/partialencode/basic/template" Uint8(uint8)
//go:generate gotemplate -outfmt %v "github.com/reddyvinod/partialencode/basic/template" Uint16(uint16)
//go:generate gotemplate -outfmt %v "github.com/reddyvinod/partialencode/basic/template" Uint32(uint32)
//go:generate gotemplate -outfmt %v "github.com/reddyvinod/partialencode/basic/template" Uint64(uint64)

//go:generate gotemplate -outfmt %v "github.com/reddyvinod/partialencode/basic/template" Float32(float32)
//go:generate gotemplate -outfmt %v "github.com/reddyvinod/partialencode/basic/template" Float64(float64)

//go:generate gotemplate -outfmt %v "github.com/reddyvinod/partialencode/basic/template" Bool(bool)
//go:generate gotemplate -outfmt %v "github.com/reddyvinod/partialencode/basic/template" String(string)
//go:generate sed -i ".bak" "s/generated by gotemplate/+build none/" template/BasicType.go
