// generated by gotemplate

package basic

import (
	"fmt"

	"github.com/reddyvinod/partialencode/jlexer"
	"github.com/reddyvinod/partialencode/jwriter"
)

// template type Int16(int16)

// int16 'gotemplate'-based type for providing optional semantics without using pointers.
type Int16 struct {
	Value int16
	Valid bool
	Set   bool
}

func (v *Int16) SetValue(val int16) {
	v.Value = val
	v.Set = true
	v.Valid = true
}

func (v *Int16) SetNull() {
	v.Set = true
	v.Valid = false
}

func (v *Int16) IsValid() bool {
	return v.Valid
}

func (v *Int16) IsSet() bool {
	return v.Set
}

func (v *Int16) Get() int16 {
	return v.Value
}

// MarshalPartialJSON does JSON marshaling using partialencode interface.
func (v Int16) MarshalPartialJSON(w *jwriter.Writer) {
	if v.Valid {
		w.Int16(v.Value)
	} else {
		w.RawString("null")
	}
}

// UnMarshalPartialJSON does JSON unmarshaling using partialencode interface.
func (v *Int16) UnMarshalPartialJSON(l *jlexer.Lexer) {
	if l.IsNull() {
		l.Skip()
		v.SetNull()
	} else {
		v.SetValue(l.Int16())
	}
}

// MarshalJSON implements a standard json marshaler interface.
func (v Int16) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	v.MarshalPartialJSON(&w)
	return w.Buffer.BuildBytes(), w.Error
}

// UnmarshalJSON implements a standard json unmarshaler interface.
func (v *Int16) UnmarshalJSON(data []byte) error {
	l := jlexer.Lexer{Data: data}
	v.UnMarshalPartialJSON(&l)
	return l.Error()
}

// String implements a stringer interface using fmt.Sprint for the value.
func (v Int16) String() string {
	if !v.Set {
		return "<undefined>"
	}
	if !v.Valid {
		return "null"
	}
	return fmt.Sprint(v.Value)
}
