// generated by gotemplate

package basic

import (
	"fmt"

	"github.com/reddyvinod/partialencode/jlexer"
	"github.com/reddyvinod/partialencode/jwriter"
)

// template type String(string)

// string 'gotemplate'-based type for providing optional semantics without using pointers.
type String struct {
	Value string
	Valid bool
	Set   bool
}

func (v *String) SetValue(val string) {
	v.Value = val
	v.Set = true
	v.Valid = true
}

func (v *String) SetNull() {
	v.Set = true
	v.Valid = false
}

func (v *String) IsValid() bool {
	return v.Valid
}

func (v *String) IsSet() bool {
	return v.Set
}

func (v *String) Get() string {
	return v.Value
}

// MarshalPartialJSON does JSON marshaling using partialencode interface.
func (v String) MarshalPartialJSON(w *jwriter.Writer) {
	if v.Valid {
		w.String(v.Value)
	} else {
		w.RawString("null")
	}
}

// UnMarshalPartialJSON does JSON unmarshaling using partialencode interface.
func (v *String) UnMarshalPartialJSON(l *jlexer.Lexer) {
	if l.IsNull() {
		l.Skip()
		v.SetNull()
	} else {
		v.SetValue(l.String())
	}
}

// MarshalJSON implements a standard json marshaler interface.
func (v String) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	v.MarshalPartialJSON(&w)
	return w.Buffer.BuildBytes(), w.Error
}

// UnmarshalJSON implements a standard json unmarshaler interface.
func (v *String) UnmarshalJSON(data []byte) error {
	l := jlexer.Lexer{Data: data}
	v.UnMarshalPartialJSON(&l)
	return l.Error()
}

// String implements a stringer interface using fmt.Sprint for the value.
func (v String) String() string {
	if !v.Set {
		return "<undefined>"
	}
	if !v.Valid {
		return "null"
	}
	return fmt.Sprint(v.Value)
}
